version: "3"

services:
  mysql-service:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
    volumes:
          - mysql:/data/mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: baye
      MYSQL_PASSWORD: Passer@1
      MYSQL_ROOT_PASSWORD: Passer@1
      MYSQL_ROOT_HOST: '%'
#  spring-service:
#    image: springservce:latest
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql-service

networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  mysql:
