version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
    volumes:
      - mysql:/data/mysql
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: baye
      MYSQL_PASSWORD: Passer@1
      MYSQL_ROOT_PASSWORD: Passer@1
      MYSQL_ROOT_HOST: '%'

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: baye
      POSTGRES_PASSWORD: passer@1
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  aeger-allinone:
    image: jaegertracing/all-in-one:1.25
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql:
