server:
  port: 9030

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: employee
          uri: lb://EMPLOYEE
          predicates:
            - Path=/api/v1/employees/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true