server:
  port: 9020

spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: baye
    password: passer@1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  cloud:
    discovery:
      enabled: true

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  file:
    path: /logs/
    name: ${spring.application.name}.log
  level:
    web: debug