server:
  port: 8761

spring:
  application:
    name: discovery-service
  cloud:
    discovery:
      enabled: true

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  logstash:
    enabled: true
    url: 127.0.0.1:5000
    logHeaders: true
