server:
  port: 9010

spring:
  application:
    name: employee

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db
    username: baye
    password: Passer@1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true


departmentService:
  url: http://DEPARTMENT/api/v1/departments/

logging:
  file:
    path: /
    name: application-log.txt
  level:
    web: debug