server:
  port: 9010

spring:
  application:
    name: employee

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee_db
    username: baye
    password: Passer@1

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true

  cloud:
    discovery:
      enabled: true


  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true


departmentService:
  url: http://DEPARTMENT/api/v1/departments/

logging:
  file:
    path: /logs/
    name: ${spring.application.name}.log
  level:
    web: debug