server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces
